# Generated by Django 5.0 on 2023-12-24 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('callsign', models.CharField(max_length=200)),
                ('founded_year', models.IntegerField()),
                ('base_airport', models.CharField(max_length=20)),
            ],
        ),
    ]
