# Generated by Django 5.0 on 2023-12-25 02:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer_serial_number', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
                ('model', models.CharField(max_length=200)),
                ('number_of_engines', models.IntegerField()),
                ('operator_airline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aircrafts', to='base.airline')),
            ],
        ),
    ]
