# Generated by Django 5.0 on 2024-01-04 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
